################################
#		RegExpChat插件         #
#  使用正则表达式过滤聊天信息  #
#	   作者:CMD丶BLOCK_        #
#		QQ:1056293351          #
################################
#正则表达式教程详见百度
#过滤列表(可使用正则表达式，请严格遵守样式
RegExpList:
  - "(F|f).*(u|U).*(c|C).*(k|K)"
#是否取消发送消息
Cancel: false
#替换符合规则的消息为什么(不取消发送的前提下)
ReplaceChar: "*"
#是否发送警告信息
sendMessage: true
#如果是，发送什么
sendMessageChar: "你不能说脏话！"
#是否提示控制台玩家说脏话
sendToConsole: true